---
Name: silverstripe-seo
After: "*"
---
SEO_Extension:
  social_image_size: 1024
  social_image_folder: 'Social'

SiteConfig:
  extensions:
    - SEO_SiteConfigExtension

File:
  Extensions:
    - SEO_SitemapImageExtension

SEO_ModelAdmin:
  models:
    - Page
    - ErrorPage

LeftAndMain:
  extra_requirements_css:
    - seo/css/seo.css

SEO_Sitemap:
  objects:
    Page:
      parent_id: 0