---
Name: seo routes config
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'sitemap.xml' : 'CyberDuck\SEO\Controller\SitemapXMLController'
    'robots.txt' : 'CyberDuck\SEO\Controller\RobotsTxtController'